#!/bin/bash
#
# Checking if server is ready
#
# (C) Copyright 2009 Nuxeo SA (http://nuxeo.com/) and contributors.
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the GNU Lesser General Public License
# (LGPL) version 2.1 which accompanies this distribution, and is available at
# http://www.gnu.org/licenses/lgpl.html
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# Lesser General Public License for more details.
#
# Contributors:
#   Julien Carsique
#
# $Id$

error=
echo "### Checking if server is ready for Nuxeo replication..."
if [ ! -d $PGDATA ]; then
    error=1
    echo "### ERROR: PostgreSQL DATA $PGDATA is not initialized"
fi
if [ -z "`id -Gn postgres|grep nuxeo`" ]; then
    error=1
    echo "### ERROR: postgres user is not part of nuxeo group"
fi
ssh -q -o "BatchMode=yes" $COMMON_USER@$SLAVE exit
if [ $? != 0 ]; then
    error=1
    echo "### ERROR: cannot connect on $SLAVE as $COMMON_USER"
fi
$SUPGROOT "ssh -q -o \"BatchMode=yes\" $COMMON_USER@$SLAVE exit"
if [ $? != 0 ]; then
    error=1
    echo "### ERROR: $PGROOT cannot connect on $SLAVE as $COMMON_USER"
fi
$SUPGROOT "ssh -q -o \"BatchMode=yes\" $PGROOT@$SLAVE exit"
if [ $? != 0 ]; then
    error=1
    echo "### ERROR: $PGROOT cannot connect on $SLAVE as $PGROOT"
fi
$SUNXUSER "touch $NXDATA/check.test" && \
$SUPGROOT "cp $NXDATA/check.test $PGDATA_BASE/check.test"
if [ $? != 0 ]; then
    error=1
    echo "### ERROR: $PGROOT cannot copy files in $NXDATA created by $COMMON_USER"
fi
$SUNXUSER "rm $NXDATA/check.test" && $SUPGROOT "rm $PGDATA_BASE/check.test"

# TODO other points to check...

if [ ! -z $error ]; then
    echo "### ERROR: you need to fix the previous errors."
    exit 1
fi
echo "### Server `uname -n` is ready."
