#!/bin/bash
#
# Cleanup useless files on slave.
# Must be run after a successful restore.
#
# (C) Copyright 2009 Nuxeo SA (http://nuxeo.com/) and contributors.
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the GNU Lesser General Public License
# (LGPL) version 2.1 which accompanies this distribution, and is available at
# http://www.gnu.org/licenses/lgpl.html
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# Lesser General Public License for more details.
#
# Contributors:
#   Julien Carsique
#
# $Id$

$SUPGROOT $SH <<EOF
  [ "$DEBUG" == true ] && set -x
  rm -f $PGDATA_BASE/backup-*.tar
  rm -rf $PGDATA_BASE/`basename $PGDATA`.backup-*
EOF
$SUNXUSER $SH <<EOF
  [ "$DEBUG" == true ] && set -x
  rm -rf $NXDATA_BASE/`basename $NXDATA`.backup-*
EOF
echo "### Slave server `uname -n` cleaned up from temporary and backup files."
