#!/bin/bash
#
# Cleanup useless files on master.
# Must be run after a successful backup.
#
# (C) Copyright 2009 Nuxeo SA (http://nuxeo.com/) and contributors.
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the GNU Lesser General Public License
# (LGPL) version 2.1 which accompanies this distribution, and is available at
# http://www.gnu.org/licenses/lgpl.html
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# Lesser General Public License for more details.
#
# Contributors:
#   Julien Carsique
#
# $Id$

find $PGDATA_BASE -name "backup-*.tar" -a ! -name `cat $PGDATA_BASE/lastbackup` -exec rm -f {} \;
echo "### Master server `uname -n` cleaned up from temporary and backup files."
